# ruff_config.toml - standalone
output-format = "concise"
preview = true
lint.select = ["N815",
		#unnecessary whitespaces
		"E201",
		"E202",
		"E203",
		"E211",
		"E225",
		"E226",
		"E227",
		"E228",
		"E231",
		"E252",
		"E275",
		"W291",
		"W293",
		"RET504",	#unnecessary assignment
		"F823",		#undefined-local
		"PLR6104",	#non-augmented-assignment
		"PLW0642",	#self-or-cls-assignment
		"RUF018",	#assignment-in-assert
		"FURB187",	#list-reverse-copy -- optional for now
		"E301",		#blank-line-between-methods //TO ADD READABILITY
		"SIM102",	#collapsible-if //TO ADD
		"PLW3301",	#nested-min-max
		"F406",		#undefined-local-with-nested-import-star-usage
		"E306",		#blank-lines-before-nested-definition //TO ADD
		"E301",		#blank-line-between-methods //TO ADD
]
line-length = 100
target-version = "py310"

[format]
quote-style = "double"
