# ruff_config.toml - standalone
output-format = "concise"
preview = true
lint.select = ["N815",
		#unnecessary whitespaces
		"E201",
		"E202",
		"E203",
		"E211",
		"E225",
		"E226",
		"E227",
		"E228",
		"E231",
		"E252",
		"E275",
		"W291",
		"W293"
]
line-length = 100
target-version = "py310"

[format]
quote-style = "double"
